# Generated by Django 3.2.25 on 2024-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0007_auto_20231105_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
